---
abstract: 'Provides an easy to use API for the creation and management of passwords in a secure manner'
author:
  - 'Günter Grodotzki <guenter@perlhipster.com>'
build_requires:
  Test::More: 0
  autodie: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  autodie: 0
  strict: 0
  utf8: 0
  warnings: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Passwords
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Crypt::Eksblowfish::Bcrypt: 0.009
  Data::Entropy::Algorithms: 0.007
  autodie: 0
  perl: 5.01
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/lifeofguenter/p5-passwords/issues
  homepage: http://www.perlhipster.com/p5-passwords
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lifeofguenter/p5-passwords.git
version: 0.01
